config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  authenticate :user, lambda { |u| u.is_admin? } do
    mount Sidekiq::Web, at: 'admin/sidekiq', as: :sidekiq
  end

  devise_for :users, path: 'auth', controllers: {
    # omniauth_callbacks: 'auth/omniauth_callbacks',
    # sessions:           'auth/sessions',
    registrations:      'auth/registrations',
    # passwords:          'auth/passwords',
    # confirmations:      'auth/confirmations',
  }

  root to: 'stories#index'

  get '.well-known/host-meta', to: 'well_known/host_meta#show', as: :host_meta, defaults: { format: 'xml' }
  get '.well-known/webfinger', to: 'well_known/webfinger#show', as: :webfinger
  get '.well-known/x-nodeinfo2', to: 'well_known/nodeinfo2#show', as: :nodeinfo2

  resource :account, path: '@:username' do
    root to: 'accounts/stories#hot'
    get :recent, to: 'accounts/stories#recent', as: :recent_stories

    resources :comments, only: [] do
      root to: 'accounts/comments#hot'
      get :recent, on: :collection, controller: 'accounts/comments'
    end
  end

  get '/stories/:id', to: redirect('/posts/%{id}')

  namespace :dashboard do
    resource :followed_accounts, only: [:show] do
      get :recent, on: :member
    end
  end

  resources :stories, path: :posts do
    get :recent, on: :collection
  end

  resources :tags, param: :name, only: [] do
    resources :stories, path: '/', controller: 'tags/stories', only: [] do
      get '/', action: :hot, on: :collection
      get :recent, on: :collection
    end
  end

  resources :comments, only: [:index, :show] do
    get :recent, on: :collection
  end

  resources :notifications, only: [:index] do
    get :unread, on: :collection
  end

  get '/ap/accounts/:username', to: redirect('/@%{username}')
  get '/ap/stories/:id', to: redirect('/stories/%{id}')
  get '/ap/comments/:id', to: redirect('/comments/%{id}')

  namespace :activitypub, path: :ap do
    resources :accounts, only: [], param: :username do
      get :outbox, on: :member

      resource :inbox, only: [:create], controller: 'account/inbox'
    end
  end

  namespace :api do
    # Salmon
    post '/salmon/:id', to: 'salmon#update', as: :salmon

    namespace :ujs do
      resources :stories, only: [] do
        post :toggle_vote, on: :member
        post :scrap, on: :member
      end

      resources :comments, only: [:new, :create, :edit, :update] do
        post :toggle_vote, on: :member
      end

      resources :accounts, only: [] do
        post :toggle_follow, on: :member
      end
    end

    namespace :v1 do
      post 'tools/scrap_url', controller: :tools, action: :scrap_url

      resources :notifications, only: [] do
        get :unread_count, on: :collection
      end

      resources :tags, only: [:index]
    end
  end

  namespace :settings do
    resource :profile, only: [:show, :update]
  end

  namespace :admin do
    resource :settings, only: [:edit, :update]
  end
end

app/views/shared/_flash.html.slim
.flashes(data-controller="flashes")
  - flash.each do |severity, value|
    .flashes-item(
      data-severity=severity
      data-value=value
      data-target="flashes.item"
    )

app/views/shared/_follow_btn.html.slim
a.btn.btn-wider.btn-sm(class=presenter.root_class
                       data-controller="follow-btn"
                       data-follow-btn-action-path=toggle_follow_api_ujs_account_path(presenter.account)
                       data-follow-btn-following=presenter.following?.to_s
                       data-follow-btn-username=presenter.account.username
                       data-action="click->follow-btn#toggle")

  i.fe.mr-2(class=presenter.icon_class)
  = presenter.label

app/views/shared/_footer.html.slim
footer.text-center
  p powered by <a href="https://gitlab.com/mbajur/prismo"><span>△</span> Prismo</a> #{Prismo::Version}

app/views/shared/_head.html.slim
meta(name="current-account-id" content=current_account&.id)
link(id="favicon" rel="icon" href="/favicon.png" type="image/png" sizes="16x16" data-controller="favicon")

app/views/shared/_navbar.html+phone.slim
header.navbar-main
  .container
    .navbar
      section.navbar-section
        = render 'shared/_navbar/jumpbox'

      section.navbar-section
        = active_link_to new_story_path, class: 'btn btn-link' do
          i.fe.fe-plus-circle

        - if user_signed_in?
          = render 'shared/_navbar/notifications'
          = render 'shared/_navbar/profile'
        - else
          = active_link_to new_user_session_path, class: 'btn btn-link' do
            i.fe.fe-user

app/views/shared/_navbar.html.slim
header.navbar-main
  .container
    .navbar
      section.navbar-section
        = link_to Setting.site_title, root_path, class: 'navbar-brand'
        = render 'shared/_navbar/jumpbox'

      section.navbar-section
        = active_link_to '+ Add story', new_story_path, class: 'btn btn-link'

        - if user_signed_in?
          = render 'shared/_navbar/notifications'
          = render 'shared/_navbar/profile'
        - else
          = link_to 'Join us', new_user_session_path, class: 'btn btn-link'

app/views/shared/_popular_tags.html.slim
- tags = TagsQuery.new.popular.first(10).map(&:decorate)

.box.mb-2.popular-tags
  .box-body
    ul.list-inline
      - tags.each do |tag|
        li.list-inline-item
          a(href=tag.path) ##{tag.name}

app/views/shared/_sentry.erb
<% if ENV.key?('SENTRY_DSN_FE') %>
  <script src="https://cdn.ravenjs.com/3.19.1/raven.min.js" crossorigin="anonymous"></script>
<% end %>