config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  authenticate :user, lambda { |u| u.is_admin? } do
    mount Sidekiq::Web, at: 'admin/sidekiq', as: :sidekiq
  end

  devise_for :users, path: 'auth', controllers: {
    # omniauth_callbacks: 'auth/omniauth_callbacks',
    # sessions:           'auth/sessions',
    registrations:      'auth/registrations',
    # passwords:          'auth/passwords',
    # confirmations:      'auth/confirmations',
  }

  root to: 'stories#index'

  get '.well-known/host-meta', to: 'well_known/host_meta#show', as: :host_meta, defaults: { format: 'xml' }
  get '.well-known/webfinger', to: 'well_known/webfinger#show', as: :webfinger
  get '.well-known/x-nodeinfo2', to: 'well_known/nodeinfo2#show', as: :nodeinfo2

  resource :account, path: '@:username' do
    root to: 'accounts/stories#hot'
    get :recent, to: 'accounts/stories#recent', as: :recent_stories

    resources :comments, only: [] do
      root to: 'accounts/comments#hot'
      get :recent, on: :collection, controller: 'accounts/comments'
    end
  end

  get '/stories/:id', to: redirect('/posts/%{id}')

  namespace :dashboard do
    resource :followed_accounts, only: [:show] do
      get :recent, on: :member
    end
  end

  resources :stories, path: :posts do
    get :recent, on: :collection
  end

  resources :tags, param: :name, only: [] do
    resources :stories, path: '/', controller: 'tags/stories', only: [] do
      get '/', action: :hot, on: :collection
      get :recent, on: :collection
    end
  end

  resources :comments, only: [:index, :show] do
    get :recent, on: :collection
  end

  resources :notifications, only: [:index] do
    get :unread, on: :collection
  end

  get '/ap/accounts/:username', to: redirect('/@%{username}')
  get '/ap/stories/:id', to: redirect('/stories/%{id}')
  get '/ap/comments/:id', to: redirect('/comments/%{id}')

  namespace :activitypub, path: :ap do
    resources :accounts, only: [], param: :username do
      get :outbox, on: :member

      resource :inbox, only: [:create], controller: 'account/inbox'
    end
  end

  namespace :api do
    # Salmon
    post '/salmon/:id', to: 'salmon#update', as: :salmon

    namespace :ujs do
      resources :stories, only: [] do
        post :toggle_vote, on: :member
        post :scrap, on: :member
      end

      resources :comments, only: [:new, :create, :edit, :update] do
        post :toggle_vote, on: :member
      end

      resources :accounts, only: [] do
        post :toggle_follow, on: :member
      end
    end

    namespace :v1 do
      post 'tools/scrap_url', controller: :tools, action: :scrap_url

      resources :notifications, only: [] do
        get :unread_count, on: :collection
      end

      resources :tags, only: [:index]
    end
  end

  namespace :settings do
    resource :profile, only: [:show, :update]
  end

  namespace :admin do
    resource :settings, only: [:edit, :update]
  end
end

app/views/shared/_navbar/_jumpbox.html.slim
- jumpbox = Jumpbox.instance
- current_link = current_jumpbox_link

.dropdown.jumpbox(data-controller="jumpbox")
  a.btn.btn-link(data-action="click->jumpbox#toggle click@window->jumpbox#windowClicked" title=current_link)
    .tile.tile-centered
      .tile-icon
        - if current_link.media_type == :icon
          i(class=current_link.media_class)
        - elsif current_link.media_type == :avatar
          img.avatar.avatar-xs(src=current_link.media)

      .tile-content
        = current_link

  ul.menu
    li.divider(data-content="Prismo feeds")

    - jumpbox.prismo_feeds.each do |link|
      - next if link.opts[:auth_required] && !user_signed_in?

      li.menu-item
        = active_link_to link.path, link.link_opts do
          .tile
            .tile-icon
              i(class=link.media_class)
            .tile-content
              = link.label

app/views/shared/_navbar/_notifications.html.slim
a.btn.btn-link.navbar-main-notifications#notifications-indicator(
  href=notifications_path
  data-controller="notifications-indicator"
  data-turbolinks-permanent=true
  data-notifications-indicator-all-path=notifications_path
  data-notifications-indicator-unread-path=unread_notifications_path
  title="Notifications"
)
  / i.icon.icon-message
  i.fe.fe-bell

app/views/shared/_navbar/_profile.html.slim
.dropdown.dropdown-right.navbar-main-profile
  a.btn.btn-link.dropdown-toggle(href="javascript:void(0);")
    = image_tag current_account.avatar_url(:size_60), class: 'avatar'

  ul.menu
    li.menu-item
      .tile.tile-centered
        .tile-icon
          = image_tag current_account.avatar_url(:size_60), class: 'avatar'
        .tile-content = current_account

    li.divider
    li.menu-item
      = link_to 'My Profile', current_account.path
    li.menu-item
      = link_to 'Settings', settings_profile_path

    - if current_user.is_admin?
      li.menu-item
        = link_to 'Admin', edit_admin_settings_path

    li.divider
    li.menu-item
      = link_to 'Sign-out', destroy_user_session_path, data: { method: "delete" }